In [1]:
a=10
type(a)

int

In [2]:
import  numpy as np

In [3]:
arr=np.array(a)
type(arr)

numpy.ndarray

In [4]:
np.ndim(a)

0

In [5]:
d=np.array([1,2,3,4])
d

array([1, 2, 3, 4])

In [6]:
np.ndim(d)

1

In [7]:
b=np.array([[1,2,3],[4,5,6]])
type(b)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.ndim(b)

2

In [9]:
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[9,10,11]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [10]:
np.ndim(c)

3

In [11]:
# array properties
#ndim
#shape
#size
#dtype

In [12]:
c.shape

(2, 2, 3)

In [13]:
b.shape

(2, 3)

In [14]:
c.size

12

In [15]:
c.dtype

dtype('int64')

In [16]:
a1=np.arange(0,100,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [17]:
#21,70, even
a2=np.arange(22,71,2)
a2

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [18]:
#20,71,odd
a3=np.arange(21,72,2)
a3

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [19]:
a3.dtype

dtype('int64')

In [20]:
a3=a3.astype("float")

In [21]:
a3.dtype

dtype('float64')

In [22]:
#linspace
ar3=np.linspace(1,100,20)
ar3

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [23]:
#indexing
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [24]:
c[1][1][0]

np.int64(9)

In [25]:
c.shape

(2, 2, 3)

In [26]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
b[1][0]

np.int64(4)

In [28]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [29]:
a[1]

np.int64(2)

In [30]:
#slicing

In [31]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# print(b[0][0])
# print(b[0][1])
# print(b[0][2])

In [33]:
b[:2,:2]

array([[1, 2],
       [4, 5]])

In [34]:
b[0:,:-1]

array([[1, 2],
       [4, 5]])

In [35]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [36]:
c[1,1,:]

array([ 9, 10, 11])

In [37]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [38]:
c[0,1,0:2]

array([4, 5])

In [39]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [40]:
c[1,1,1:3]

array([10, 11])

In [41]:
#practice
mat=np.arange(1,37)
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [42]:
mat=mat.reshape(6,6)
mat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [43]:
mat[1:4,2:5]

array([[ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])

In [44]:
#every 2nd row,2nd col
mat[::2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [45]:
#reverse rows without chnaging coluns
mat[:,::-1]

array([[ 6,  5,  4,  3,  2,  1],
       [12, 11, 10,  9,  8,  7],
       [18, 17, 16, 15, 14, 13],
       [24, 23, 22, 21, 20, 19],
       [30, 29, 28, 27, 26, 25],
       [36, 35, 34, 33, 32, 31]])

In [46]:
#middle
mat[2:4,2:4]

array([[15, 16],
       [21, 22]])

In [47]:
#vectorization cannot be done in lists we need loops or function

def fun(l):
    return l*5
l=[1,2,3,4,5]

m=list(map(fun,l))
m

[5, 10, 15, 20, 25]

In [48]:
#vectorization in arrays
la=np.array(l)
print(la*5)

[ 5 10 15 20 25]


In [49]:
#broadcasting

a=[1,2,3]
print(a)
b=[[4],[5],[6]]
print(b)
a+b

[1, 2, 3]
[[4], [5], [6]]


[1, 2, 3, [4], [5], [6]]

In [50]:
a=np.array([1,2,3])
print(a)
b=np.array([[4],[5],[6]])
print(b)
c=a+b
c

[1 2 3]
[[4]
 [5]
 [6]]


array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [51]:
np.ndim(a)

1

In [52]:
np.ndim(b)

2

In [53]:
np.ndim(c)

2

In [54]:
#math fun
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [55]:
np.sum(c)

np.int64(63)

In [56]:
np.max(c)

np.int64(9)

In [57]:
np.min(c)

np.int64(5)

In [58]:
np.mean(c)

np.float64(7.0)

In [59]:
np.median(c)

np.float64(7.0)

In [60]:
np.log(c)

array([[1.60943791, 1.79175947, 1.94591015],
       [1.79175947, 1.94591015, 2.07944154],
       [1.94591015, 2.07944154, 2.19722458]])

In [61]:
np.sqrt(c)

array([[2.23606798, 2.44948974, 2.64575131],
       [2.44948974, 2.64575131, 2.82842712],
       [2.64575131, 2.82842712, 3.        ]])

In [62]:
np.exp(c)

array([[ 148.4131591 ,  403.42879349, 1096.63315843],
       [ 403.42879349, 1096.63315843, 2980.95798704],
       [1096.63315843, 2980.95798704, 8103.08392758]])

In [63]:
np.std(c)

np.float64(1.1547005383792515)

In [64]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [65]:
np.dot(a,b)

array([32])

In [66]:
a@b

array([32])

In [67]:
np.random.rand(4,4)

array([[0.09472043, 0.96065619, 0.26644018, 0.568712  ],
       [0.16920795, 0.77209081, 0.56745898, 0.21265893],
       [0.54828704, 0.64263391, 0.84820997, 0.39914008],
       [0.13547457, 0.10821403, 0.52935417, 0.81077657]])

In [68]:
np.random.randint(1,1000,5)

array([322, 273, 221, 664, 598], dtype=int32)

In [69]:
np.random.normal(8,2,100)#mean.std,size

array([ 8.11985757,  7.30126376,  8.63533266,  3.59369077,  8.28673213,
        8.79794962,  9.0203104 ,  7.23477379,  8.96341295,  6.446998  ,
        6.99114872,  7.98874547, 11.88617832,  9.47644093,  6.94457074,
        9.25374564,  4.48778532,  5.78279504,  5.26353986,  8.91188694,
        4.10947691,  9.75651139, 10.70609297,  9.82256635,  4.18010413,
        7.46071073,  5.09736503,  9.08627843,  5.97083165,  7.48442046,
       10.71316591,  9.77669269,  5.32364176,  6.91482363,  6.31745798,
        9.77750772, 10.4142901 , 12.55402974,  8.28651051,  6.14777256,
        8.97044899,  8.19252622,  8.01251015,  9.52931172,  9.15596438,
       12.08823799,  7.95349899,  7.55999199,  8.87019784,  9.38129701,
        9.83940347,  8.64007909,  5.88277431,  8.03744715, 12.19688193,
        4.77620721,  9.62895143,  8.267533  ,  6.98931352,  6.5893082 ,
        6.38266332, 14.66436258,  6.59572467,  5.29562324,  7.95667295,
        8.86507021,  6.78050322,  7.79633799, 10.52538815, 11.67

In [70]:
#check if my res has same mean,std
ans=np.array([ 9.00977297,  0.65856103,  5.68066668,  8.55947942,  6.36631923,
        6.27892869,  8.55101171,  8.30440369,  5.00325149,  3.66277591,
        5.36793335,  7.60373521,  9.94507821,  6.83887291,  7.26884692,
        7.47150873,  8.65550872,  6.15051055,  5.30439811,  6.1877364 ,
        7.39669924,  7.4369926 , 10.6495616 ,  8.96941711,  8.21808451,
        9.57382746,  8.36234274,  5.9328308 ,  7.46602527,  9.95667098,
        4.31843863,  9.6803947 ,  6.65323456,  6.62411023,  8.38360806,
        7.88996327,  7.81806241,  5.56123701, 11.25444743,  9.40537858,
       10.31909648,  3.89304879,  6.89204958,  6.06886231,  7.25600754,
        8.28729476,  7.44808685, 10.771968  , 10.49498794,  7.7907104 ,
        6.23878743,  6.71003802,  6.8886789 ,  7.94351817,  8.74499357,
       12.00046126,  5.17652843,  3.55261115, 10.31697155,  9.23753933,
        7.81470143,  5.41070272,  5.10529716,  5.35197441,  9.45807276,
        7.9855475 ,  6.42214009,  7.56512819,  7.84457674,  9.24106476,
        6.39363962,  9.52814952,  8.67753456,  7.33464471,  7.73658223,
        6.38961179,  8.64173264,  6.48432673,  8.5726984 ,  6.32950202,
        9.2373224 ,  7.65587755,  4.8664776 ,  5.34090382,  7.95374847,
        8.65900806,  9.14904021,  6.82820409, 12.43303663,  9.05907616,
       10.59535577, 12.44241231, 10.80154701,  8.79520362,  7.70836769,
        7.2429636 ,  9.20345694,  8.21371442,  7.34305408,  6.99718494])

In [71]:
np.mean(ans)

np.float64(7.692664509299999)

In [72]:
np.std(ans)

np.float64(1.984913734406905)

In [73]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [74]:
#boolean indexing-- filtering
print(c>7)

[[False False False]
 [False False  True]
 [False  True  True]]


In [75]:
#reshaping transform
print(c.reshape(-1,1)) #ml models input
print(c.reshape(1,-1))

[[5]
 [6]
 [7]
 [6]
 [7]
 [8]
 [7]
 [8]
 [9]]
[[5 6 7 6 7 8 7 8 9]]


In [76]:
c.flatten()

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [77]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [78]:
c.ravel()

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [79]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [80]:
np.vstack(c)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [81]:
np.hstack(c)

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [84]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [85]:
np.sort(c)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [91]:
np.hsplit(c,3)

[array([[5],
        [6],
        [7]]),
 array([[6],
        [7],
        [8]]),
 array([[7],
        [8],
        [9]])]

In [89]:
np.vsplit(c,3)

[array([[5, 6, 7]]), array([[6, 7, 8]]), array([[7, 8, 9]])]

In [94]:
np.sum(c,axis=0)

array([18, 21, 24])

In [95]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])