In [1]:
a=10
type(a)

int

In [2]:
import  numpy as np

In [3]:
arr=np.array(a)
type(arr)

numpy.ndarray

In [4]:
np.ndim(a)

0

In [5]:
d=np.array([1,2,3,4])
d

array([1, 2, 3, 4])

In [6]:
np.ndim(d)

1

In [7]:
b=np.array([[1,2,3],[4,5,6]])
type(b)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.ndim(b)

2

In [9]:
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[9,10,11]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [10]:
np.ndim(c)

3

In [11]:
# array properties
#ndim
#shape
#size
#dtype

In [12]:
c.shape

(2, 2, 3)

In [13]:
b.shape

(2, 3)

In [14]:
c.size

12

In [15]:
c.dtype

dtype('int64')

In [16]:
a1=np.arange(0,100,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [17]:
#21,70, even
a2=np.arange(22,71,2)
a2

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [18]:
#20,71,odd
a3=np.arange(21,72,2)
a3

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [19]:
a3.dtype

dtype('int64')

In [20]:
a3=a3.astype("float")

In [21]:
a3.dtype

dtype('float64')

In [22]:
#linspace
ar3=np.linspace(1,100,20)
ar3

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [23]:
#indexing
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [31]:
c[1][1][0]

np.int64(9)

In [32]:
c.shape

(2, 2, 3)

In [24]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
b[1][0]

np.int64(4)

In [26]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [27]:
a[1]

np.int64(2)

In [28]:
#slicing